- name: Start app
  supervisorctl:
    name: "{{ item.name }}"
    state: restarted
    config: /etc/supervisor/supervisord.conf
    supervisorctl_path: "/usr/bin/supervisorctl"
  become: yes
  with_items: "{{ supervisor_apps }}"
  tags:
    - supervisord