- name: "Clean /home/{{ user_name }}/{{ project_dir }}"
  file: path=/home/{{ user_name }}/{{ project_dir }} state=absent mode=0700 owner={{ user_name }} group={{ user_name }}
  become: yes

- name: "Create /home/{{ user_name }}/{{ project_dir }}"
  file: path=/home/{{ user_name }}/{{ project_dir }} state=directory mode=0755 owner={{ user_name }} group={{ user_name }}
  become: yes