- name: Add apt repository for postgresql-9.5
  apt_repository:
    repo: deb https://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
    state: present
    update_cache: yes
  become: yes

- name: Run "apt-get install postgresql-client-9.5"
  apt:
    pkg: postgresql-client-9.5
    state: present
    allow_unauthenticated: yes
  become: yes
