- name: Creating application user
  user: name={{ user_name }} shell=/bin/bash home=/home/{{ user_name }}
  become: yes

- name: Enable code access for the application user
  file: path=/home/{{ user_name }}/.ssh state=directory mode=0700 owner={{ user_name }} group={{ user_name }}
  become: yes

- name: Validating host key
  shell: ssh-keyscan bitbucket.org >> /home/{{ user_name }}/.ssh/known_hosts
  become: yes
  become_user: "{{ user_name }}"