---
  - name: Playbook for installation, software, application
    hosts: localhost
    serial: 1

    vars_files:
      - ../group_vars/all

    tasks:
      - include: ../ansible/tasks/setup_user.yml

      - include: ../ansible/tasks/clean_project_dir.yml

      - include: ../ansible/tasks/install_base_pkgs.yml

      - include: ../ansible/tasks/git_clone_repo.yml

      - include: ../ansible/tasks/requirements.yml

      - include: ../ansible/tasks/bash_rc.yml

      - name: Create log directories
        file: path=/var/log/apps/{{ app_name }}/ state=directory mode=0755 owner={{ user_name }} group={{ user_name }}
        become: yes

      - name: copy uwsgi.ini to codebase
        template: src=../templates/uwsgi.ini.j2 dest=/home/{{ user_name }}/{{ project_dir }}/uwsgi.ini owner={{ user_name }} group={{ user_name }}

#      - name: Generating upstart file
#        template: src=../templates/upstart_service.conf.j2 dest=/etc/init/{{ app_name }}.conf
#        become: yes

      - name: Run nginx role
        include_role:
          name: nginx
        become: yes

      - name: Run supervisor role
        include_role:
          name: supervisor

      - name: Run DB migrations
        shell: "flask db upgrade"

      - name: Ensure supervisor service is started
        service: name=supervisor state=restarted enabled=yes
        become: yes

      - name: Start application server (uwsgi)
        include: ../ansible/tasks/app_server.yml

      - include: ../ansible/tasks/postgres-client.yml
        tags:
          - user_data